name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deno ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version: ["v1.4", "v1.5", "nightly"]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Check mod.ts
      run: time deno cache --reload mod.ts
    - name: Check example.ts
      run: time deno cache example.ts
    - name: Check examples/emit-metrics.ts
      run: time deno cache --unstable examples/emit-metrics.ts
